import type { Metadata } from "next";
import localFont from "next/font/local";
import {
  Dancing_Script,
  Geist,
  Geist_Mono,
  Montserrat,
  Poppins,
} from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/context/ModalContext";

const montSerrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const amertha = localFont({
  src: "../../public/fonts/Amertha.ttf",
  variable: "--font-amertha",
});
const bylinerScript = localFont({
  src: "../../public/fonts/BylinerScript.otf",
  variable: "--font-byliner",
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancingScript",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dancingScript.variable} ${amertha.variable} ${montSerrat.variable} ${poppins.variable} ${bylinerScript.variable}`}
    >
      <body>
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}
